
package clienteserviciohora;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImplementacionServicioHoraService", targetNamespace = "http://serviciohora/", wsdlLocation = "http://localhost:7001/EjemploServicioHoraFromJava/ImplementacionServicioHoraService?wsdl")
public class ImplementacionServicioHoraService
    extends Service
{

    private final static URL IMPLEMENTACIONSERVICIOHORASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clienteserviciohora.ImplementacionServicioHoraService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clienteserviciohora.ImplementacionServicioHoraService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/EjemploServicioHoraFromJava/ImplementacionServicioHoraService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/EjemploServicioHoraFromJava/ImplementacionServicioHoraService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IMPLEMENTACIONSERVICIOHORASERVICE_WSDL_LOCATION = url;
    }

    public ImplementacionServicioHoraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImplementacionServicioHoraService() {
        super(IMPLEMENTACIONSERVICIOHORASERVICE_WSDL_LOCATION, new QName("http://serviciohora/", "ImplementacionServicioHoraService"));
    }

    /**
     * 
     * @return
     *     returns ImplementacionServicioHora
     */
    @WebEndpoint(name = "ImplementacionServicioHoraPort")
    public ImplementacionServicioHora getImplementacionServicioHoraPort() {
        return super.getPort(new QName("http://serviciohora/", "ImplementacionServicioHoraPort"), ImplementacionServicioHora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImplementacionServicioHora
     */
    @WebEndpoint(name = "ImplementacionServicioHoraPort")
    public ImplementacionServicioHora getImplementacionServicioHoraPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviciohora/", "ImplementacionServicioHoraPort"), ImplementacionServicioHora.class, features);
    }

}
