
package clienteserviciohora;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ImplementacionServicioHora", targetNamespace = "http://serviciohora/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImplementacionServicioHora {


    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws ServicioHoraException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHora", targetNamespace = "http://serviciohora/", className = "clienteserviciohora.GetHora")
    @ResponseWrapper(localName = "getHoraResponse", targetNamespace = "http://serviciohora/", className = "clienteserviciohora.GetHoraResponse")
    public String getHora()
        throws ServicioHoraException_Exception
    ;

}
