
package clienteservicio;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ErrorServicioWeb", targetNamespace = "http://prueba.inap.minhap.gob.es")
public class InfoFicheroException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServicioWebError faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InfoFicheroException(String message, ServicioWebError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InfoFicheroException(String message, ServicioWebError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: clienteservicio.ServicioWebError
     */
    public ServicioWebError getFaultInfo() {
        return faultInfo;
    }

}
