
package clienteservicio;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PruebaServicio", targetNamespace = "http://prueba.inap.minhap.gob.es")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PruebaServicio {


    /**
     * 
     * @param pathCompletoFichero
     * @return
     *     returns clienteservicio.InfoFichero
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "Resultado", targetNamespace = "")
    @RequestWrapper(localName = "getInfoFichero", targetNamespace = "http://prueba.inap.minhap.gob.es", className = "clienteservicio.GetInfoFichero")
    @ResponseWrapper(localName = "getInfoFicheroResponse", targetNamespace = "http://prueba.inap.minhap.gob.es", className = "clienteservicio.GetInfoFicheroResponse")
    public InfoFichero getInfoFichero(
        @WebParam(name = "PathCompletoFichero", targetNamespace = "")
        String pathCompletoFichero)
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @param fichero
     * @param nombreFichero
     * @param tipoFichero
     * @return
     *     returns clienteservicio.InfoFichero
     * @throws FileNotFoundException_Exception
     * @throws InfoFicheroException
     */
    @WebMethod
    @WebResult(name = "Resultado", targetNamespace = "")
    @RequestWrapper(localName = "getFicheroConInfo", targetNamespace = "http://prueba.inap.minhap.gob.es", className = "clienteservicio.GetFicheroConInfo")
    @ResponseWrapper(localName = "getFicheroConInfoResponse", targetNamespace = "http://prueba.inap.minhap.gob.es", className = "clienteservicio.GetFicheroConInfoResponse")
    public InfoFichero getFicheroConInfo(
        @WebParam(name = "NombreFichero", targetNamespace = "")
        String nombreFichero,
        @WebParam(name = "TipoFichero", targetNamespace = "")
        TipoDeFichero tipoFichero,
        @WebParam(name = "Fichero", targetNamespace = "")
        DataHandler fichero)
        throws FileNotFoundException_Exception, InfoFicheroException
    ;

}
