
package clienteservicio;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsPrueba", targetNamespace = "http://prueba.inap.minhap.gob.es", wsdlLocation = "http://localhost:7001/E9e-EjemploInfoFichero/wsPrueba?wsdl")
public class WsPrueba
    extends Service
{

    private final static URL WSPRUEBA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clienteservicio.WsPrueba.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clienteservicio.WsPrueba.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/E9e-EjemploInfoFichero/wsPrueba?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/E9e-EjemploInfoFichero/wsPrueba?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSPRUEBA_WSDL_LOCATION = url;
    }

    public WsPrueba(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsPrueba() {
        super(WSPRUEBA_WSDL_LOCATION, new QName("http://prueba.inap.minhap.gob.es", "wsPrueba"));
    }

    /**
     * 
     * @return
     *     returns PruebaServicio
     */
    @WebEndpoint(name = "PruebaPort")
    public PruebaServicio getPruebaPort() {
        return super.getPort(new QName("http://prueba.inap.minhap.gob.es", "PruebaPort"), PruebaServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PruebaServicio
     */
    @WebEndpoint(name = "PruebaPort")
    public PruebaServicio getPruebaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://prueba.inap.minhap.gob.es", "PruebaPort"), PruebaServicio.class, features);
    }

}
