
package consulta;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GestorConsultaAlojamientosRurales", targetNamespace = "http://consulta/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestorConsultaAlojamientosRurales {


    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPrecioPorPersona", targetNamespace = "http://consulta/", className = "consulta.ObtenerPrecioPorPersona")
    @ResponseWrapper(localName = "obtenerPrecioPorPersonaResponse", targetNamespace = "http://consulta/", className = "consulta.ObtenerPrecioPorPersonaResponse")
    public Integer obtenerPrecioPorPersona();

}
