
package consulta;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GestorConsultaAlojamientosRuralesService", targetNamespace = "http://consulta/", wsdlLocation = "http://localhost:7001/RuralCliente/GestorConsultaAlojamientosRuralesService?WSDL")
public class GestorConsultaAlojamientosRuralesService
    extends Service
{

    private final static URL GESTORCONSULTAALOJAMIENTOSRURALESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(consulta.GestorConsultaAlojamientosRuralesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = consulta.GestorConsultaAlojamientosRuralesService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/RuralCliente/GestorConsultaAlojamientosRuralesService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/RuralCliente/GestorConsultaAlojamientosRuralesService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GESTORCONSULTAALOJAMIENTOSRURALESSERVICE_WSDL_LOCATION = url;
    }

    public GestorConsultaAlojamientosRuralesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestorConsultaAlojamientosRuralesService() {
        super(GESTORCONSULTAALOJAMIENTOSRURALESSERVICE_WSDL_LOCATION, new QName("http://consulta/", "GestorConsultaAlojamientosRuralesService"));
    }

    /**
     * 
     * @return
     *     returns GestorConsultaAlojamientosRurales
     */
    @WebEndpoint(name = "GestorConsultaAlojamientosRuralesPort")
    public GestorConsultaAlojamientosRurales getGestorConsultaAlojamientosRuralesPort() {
        return super.getPort(new QName("http://consulta/", "GestorConsultaAlojamientosRuralesPort"), GestorConsultaAlojamientosRurales.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestorConsultaAlojamientosRurales
     */
    @WebEndpoint(name = "GestorConsultaAlojamientosRuralesPort")
    public GestorConsultaAlojamientosRurales getGestorConsultaAlojamientosRuralesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://consulta/", "GestorConsultaAlojamientosRuralesPort"), GestorConsultaAlojamientosRurales.class, features);
    }

}
