
package clienteserviciominusculas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicioMinusculas", targetNamespace = "http://serviciominusculas/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioMinusculas {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ServicioMinusculasException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMinusculas", targetNamespace = "http://serviciominusculas/", className = "clienteserviciominusculas.GetMinusculas")
    @ResponseWrapper(localName = "getMinusculasResponse", targetNamespace = "http://serviciominusculas/", className = "clienteserviciominusculas.GetMinusculasResponse")
    public String getMinusculas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServicioMinusculasException_Exception
    ;

}
