
package clienteserviciominusculas;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServicioMinusculasException", targetNamespace = "http://serviciominusculas/")
public class ServicioMinusculasException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServicioMinusculasException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServicioMinusculasException_Exception(String message, ServicioMinusculasException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServicioMinusculasException_Exception(String message, ServicioMinusculasException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: clienteserviciominusculas.ServicioMinusculasException
     */
    public ServicioMinusculasException getFaultInfo() {
        return faultInfo;
    }

}
