
package clienteserviciohoraasync;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServicioHoraException", targetNamespace = "http://serviciohora/")
public class ServicioHoraException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServicioHoraException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServicioHoraException_Exception(String message, ServicioHoraException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServicioHoraException_Exception(String message, ServicioHoraException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: clienteserviciohoraasync.ServicioHoraException
     */
    public ServicioHoraException getFaultInfo() {
        return faultInfo;
    }

}
