
package clienteservicio;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Transformacion", targetNamespace = "http://prueba.inap.minhap.gob.es")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Transformacion {


    /**
     * 
     * @param ficheroXSL
     * @param ficheroXML
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(name = "HTML", targetNamespace = "")
    @RequestWrapper(localName = "transformaXMLtoHTML", targetNamespace = "http://prueba.inap.minhap.gob.es", className = "clienteservicio.TransformaXMLtoHTML")
    @ResponseWrapper(localName = "transformaXMLtoHTMLResponse", targetNamespace = "http://prueba.inap.minhap.gob.es", className = "clienteservicio.TransformaXMLtoHTMLResponse")
    public DataHandler transformaXMLtoHTML(
        @WebParam(name = "FicheroXML", targetNamespace = "")
        DataHandler ficheroXML,
        @WebParam(name = "FicheroXSL", targetNamespace = "")
        DataHandler ficheroXSL);

}
