
package clienteservicio;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsTransformacion", targetNamespace = "http://prueba.inap.minhap.gob.es", wsdlLocation = "http://localhost:7001/Ejercicio11/wsTransformacion?WSDL")
public class WsTransformacion
    extends Service
{

    private final static URL WSTRANSFORMACION_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(clienteservicio.WsTransformacion.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = clienteservicio.WsTransformacion.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/Ejercicio11/wsTransformacion?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/Ejercicio11/wsTransformacion?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSTRANSFORMACION_WSDL_LOCATION = url;
    }

    public WsTransformacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsTransformacion() {
        super(WSTRANSFORMACION_WSDL_LOCATION, new QName("http://prueba.inap.minhap.gob.es", "wsTransformacion"));
    }

    /**
     * 
     * @return
     *     returns Transformacion
     */
    @WebEndpoint(name = "TransformacionPort")
    public Transformacion getTransformacionPort() {
        return super.getPort(new QName("http://prueba.inap.minhap.gob.es", "TransformacionPort"), Transformacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Transformacion
     */
    @WebEndpoint(name = "TransformacionPort")
    public Transformacion getTransformacionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://prueba.inap.minhap.gob.es", "TransformacionPort"), Transformacion.class, features);
    }

}
