
package rural;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GestorRegistroAlojamientosRuralesService", targetNamespace = "http://rural/", wsdlLocation = "http://localhost:7001/RuralServidor/GestorRegistroAlojamientosRuralesService?WSDL")
public class GestorRegistroAlojamientosRuralesService
    extends Service
{

    private final static URL GESTORREGISTROALOJAMIENTOSRURALESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(rural.GestorRegistroAlojamientosRuralesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = rural.GestorRegistroAlojamientosRuralesService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/RuralServidor/GestorRegistroAlojamientosRuralesService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/RuralServidor/GestorRegistroAlojamientosRuralesService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GESTORREGISTROALOJAMIENTOSRURALESSERVICE_WSDL_LOCATION = url;
    }

    public GestorRegistroAlojamientosRuralesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestorRegistroAlojamientosRuralesService() {
        super(GESTORREGISTROALOJAMIENTOSRURALESSERVICE_WSDL_LOCATION, new QName("http://rural/", "GestorRegistroAlojamientosRuralesService"));
    }

    /**
     * 
     * @return
     *     returns GestorRegistroAlojamientosRurales
     */
    @WebEndpoint(name = "GestorRegistroAlojamientosRuralesPort")
    public GestorRegistroAlojamientosRurales getGestorRegistroAlojamientosRuralesPort() {
        return super.getPort(new QName("http://rural/", "GestorRegistroAlojamientosRuralesPort"), GestorRegistroAlojamientosRurales.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestorRegistroAlojamientosRurales
     */
    @WebEndpoint(name = "GestorRegistroAlojamientosRuralesPort")
    public GestorRegistroAlojamientosRurales getGestorRegistroAlojamientosRuralesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rural/", "GestorRegistroAlojamientosRuralesPort"), GestorRegistroAlojamientosRurales.class, features);
    }

}
