
package pservicioreverso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicioReversoFromJava", targetNamespace = "http://pservicioreverso/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioReversoFromJava {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReverso", targetNamespace = "http://pservicioreverso/", className = "pservicioreverso.GetReverso")
    @ResponseWrapper(localName = "getReversoResponse", targetNamespace = "http://pservicioreverso/", className = "pservicioreverso.GetReversoResponse")
    public String getReverso(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
